name       : igsc
version    : 0.2.5
release    : 1
source     :
    - https://github.com/intel/igsc/archive/refs/tags/V0.2.5.tar.gz : d0134f7447f98ac2bdcb5cf9c01dce3051111e1a566e048d59f327327f6972d5
license    : Apache-2.0
component  : programming.tools
summary    : Intel graphics system controller firmware update library
description: |
    Intel graphics system controller firmware update library.
clang      : yes
builddeps  :
    - intel-metee-devel
    - git
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
